import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/header/header";
import RegistrationForm from "../components/registration-form/registration-form";
import styles from "../styles/index.module.css";
import layout from "../styles/layout.module.css";
import typography from "../styles/typography.module.css";
import cx from "classix";
import Link from "next/link";
import Button from "../components/button/button";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Atelier Disko Coding Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header pageName="Welcome!" />
        <div className={styles.ctas}>
          <Link href="/signup">
            <Button>Sign up</Button>
          </Link>
          <Link href="/registration/all">
            <Button>Users</Button>
          </Link>
        </div>
      </main>
    </>
  );
};

export default Home;
